### ISSUE TITLE
[BUG] Series not clickable in landscape orientation

### ISSUE THREAD

**Issue by operationairstrike** [DATL4G/BurningSeries-Android#67]
**Describe the bug**
When going back from the player and in landscape mode you can't click any series unless screen is rotated.

**To Reproduce**
1. Click on a Series
2. Start watching a episode
3. Turn orientation
4. Go back
5. Try to click a series

**Expected behavior**
Open the series site or last played stream.

**Screenshots**
https://youtu.be/jokraWT_2Ng?si=yYS_dZ41-5Wl6KP2

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T
 - OS: Android 13
 - Version Latest

**Comment by DatL4g** [comment]
Can't reproduce, the ripple effect (click animation) even indicates that the click is registered.

Gonna keep it open for now, but not sure how/when to fix it

**Comment by operationairstrike** [comment]
Ok but you've seen the video right?

**Comment by operationairstrike** [comment]
It's seems like it shows something different on the same page in landscape and portrait mode

**Comment by DatL4g** [comment]
I changed the click listener in latest release https://github.com/DatL4g/Burning-Series/releases/tag/v5.3.0 which should fix the issue.

**Comment by operationairstrike** [comment]
TYSM @DatL4g

**Comment by operationairstrike** [comment]
I just tested it sadly is still the same it doesn't go to the series site.

**Comment by DatL4g** [comment]
Please update to https://github.com/DatL4g/Burning-Series/releases/tag/v5.4.0 and check if the issue still exists
